Update Angora to the latest, LLVM 11, modified angora so the docker image compiles
Signed-off-by: Peter Rong <PeterRong96@gmail.com>

give 200M memory limit to Angora or php fails on startup

php needs to load a large dyn library libstdc++.so.6
If not enough memory is given, fast program(fork client) will crash and report:

error while loading shared libraries: libstdc++.so.6: failed to map segment from shared object

and thus hang the fuzzer.

Signed-off-by: Peter Rong <PeterRong96@gmail.com>

moved abilist. -lc++ not changed or Angora-php compile fails with linking error to std:

ext/intl/msgformat/msgformat_helpers.o: In function `std::__1::vector<icu_60::Formattable, std::__1::allocator<icu_60::Formattable> >::__append(unsigned long)':
/magma/fuzzers/angora/repo/llvm_install/clang+llvm/bin/../include/c++/v1/vector:1029: undefined reference to `std::__1::__vector_base_common<true>::__throw_length_error() const'

Signed-off-by: Peter Rong <PeterRong96@gmail.com>